apiVersion: v1
kind: Service
metadata:
  name: pseugc-app-service
spec:
  type: ClusterIP
  selector:
    app: pseugc-app
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 8501
    - name: api
      protocol: TCP
      port: 8000
      targetPort: 8000
